"""add_export_documents_table

Revision ID: 9ce82bee6880
Revises: 003
Create Date: 2026-03-26 21:12:48.907629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9ce82bee6880'
down_revision: Union[str, None] = '003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integration_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('integration_type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('base_url', sa.String(length=2048), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('encrypted_credentials', sa.Text(), nullable=True),
    sa.Column('webhook_secret', sa.Text(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'name', name='uq_integration_configs_org_name')
    )
    op.create_index('idx_integration_configs_integration_type', 'integration_configs', ['integration_type'], unique=False)
    op.create_index('idx_integration_configs_is_enabled', 'integration_configs', ['is_enabled'], unique=False)
    op.create_index('idx_integration_configs_organization_id', 'integration_configs', ['organization_id'], unique=False)
    op.create_table('change_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('change_number', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('change_type', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('compliance_justification', sa.Text(), nullable=True),
    sa.Column('affected_devices', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('affected_compliance_scopes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('requested_by', sa.UUID(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('scheduled_window_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_window_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approval_notes', sa.Text(), nullable=True),
    sa.Column('proposed_change_description', sa.Text(), nullable=True),
    sa.Column('proposed_change_hash', sa.String(length=64), nullable=True),
    sa.Column('pre_change_hash', sa.String(length=64), nullable=True),
    sa.Column('post_change_hash', sa.String(length=64), nullable=True),
    sa.Column('simulation_performed', sa.Boolean(), nullable=True),
    sa.Column('simulation_results', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('simulation_passed', sa.Boolean(), nullable=True),
    sa.Column('implemented_by', sa.UUID(), nullable=True),
    sa.Column('implemented_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('implementation_evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('verification_results', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('verification_passed', sa.Boolean(), nullable=True),
    sa.Column('rollback_plan', sa.Text(), nullable=True),
    sa.Column('rollback_performed', sa.Boolean(), nullable=True),
    sa.Column('rollback_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rollback_reason', sa.Text(), nullable=True),
    sa.Column('external_ticket_id', sa.String(length=255), nullable=True),
    sa.Column('external_ticket_url', sa.String(length=2048), nullable=True),
    sa.Column('ticket_system', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['implemented_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('change_number')
    )
    op.create_index('idx_change_records_affected_compliance_scopes', 'change_records', ['affected_compliance_scopes'], unique=False, postgresql_using='gin')
    op.create_index('idx_change_records_approved_by', 'change_records', ['approved_by'], unique=False)
    op.create_index('idx_change_records_change_number', 'change_records', ['change_number'], unique=False)
    op.create_index('idx_change_records_external_ticket_id', 'change_records', ['external_ticket_id'], unique=False)
    op.create_index('idx_change_records_organization_id', 'change_records', ['organization_id'], unique=False)
    op.create_index('idx_change_records_requested_at', 'change_records', ['requested_at'], unique=False)
    op.create_index('idx_change_records_status', 'change_records', ['status'], unique=False)
    op.create_table('export_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('requested_by', sa.UUID(), nullable=True),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('format', sa.String(length=20), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('storage_path', sa.String(length=2048), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_export_documents_created_at', 'export_documents', ['created_at'], unique=False)
    op.create_index('idx_export_documents_document_type', 'export_documents', ['document_type'], unique=False)
    op.create_index('idx_export_documents_expires_at', 'export_documents', ['expires_at'], unique=False)
    op.create_index('idx_export_documents_organization_id', 'export_documents', ['organization_id'], unique=False)
    op.create_index('idx_export_documents_requested_by', 'export_documents', ['requested_by'], unique=False)
    op.create_index('idx_export_documents_status', 'export_documents', ['status'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_name', sa.String(length=255), nullable=False),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tasks_created_at', 'tasks', ['created_at'], unique=False)
    op.create_index('idx_tasks_organization_id', 'tasks', ['organization_id'], unique=False)
    op.create_index('idx_tasks_parent_id', 'tasks', ['parent_id'], unique=False)
    op.create_index('idx_tasks_status', 'tasks', ['status'], unique=False)
    op.create_table('user_org_access',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('access_role', sa.String(length=50), nullable=False),
    sa.Column('granted_by', sa.UUID(), nullable=True),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'organization_id', name='uq_user_org_access')
    )
    op.create_index('idx_user_org_access_expires_at', 'user_org_access', ['expires_at'], unique=False)
    op.create_index('idx_user_org_access_organization_id', 'user_org_access', ['organization_id'], unique=False)
    op.create_index('idx_user_org_access_user_id', 'user_org_access', ['user_id'], unique=False)
    op.create_table('acl_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('encrypted_blob', sa.Text(), nullable=False),
    sa.Column('content_hmac', sa.String(length=64), nullable=False),
    sa.Column('plaintext_size_bytes', sa.Integer(), nullable=True),
    sa.Column('key_id', sa.String(length=500), nullable=False),
    sa.Column('key_provider', sa.String(length=50), nullable=False),
    sa.Column('encryption_algorithm', sa.String(length=50), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('captured_by', sa.UUID(), nullable=True),
    sa.Column('config_hash_at_capture', sa.String(length=64), nullable=True),
    sa.Column('compliance_scope', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['captured_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_acl_snapshots_captured_at', 'acl_snapshots', ['captured_at'], unique=False)
    op.create_index('idx_acl_snapshots_compliance_scope', 'acl_snapshots', ['compliance_scope'], unique=False, postgresql_using='gin')
    op.create_index('idx_acl_snapshots_content_type', 'acl_snapshots', ['content_type'], unique=False)
    op.create_index('idx_acl_snapshots_device_id', 'acl_snapshots', ['device_id'], unique=False)
    op.create_index('idx_acl_snapshots_organization_id', 'acl_snapshots', ['organization_id'], unique=False)
    op.create_index('idx_audit_logs_outcome', 'audit_logs', ['outcome'], unique=False)
    op.create_index('idx_audit_logs_timestamp', 'audit_logs', ['timestamp'], unique=False)
    op.add_column('credentials', sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('credentials', 'metadata')
    op.drop_index('idx_devices_config_vector', table_name='devices', postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_index('idx_devices_role_vector', table_name='devices', postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_index('idx_devices_security_vector', table_name='devices', postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_index('idx_devices_topology_vector', table_name='devices', postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.add_column('interfaces', sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('interfaces', 'metadata')
    op.create_unique_constraint(None, 'organizations', ['slug'])
    op.add_column('sites', sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('sites', 'metadata')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sites', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('sites', 'meta')
    op.drop_constraint(None, 'organizations', type_='unique')
    op.add_column('interfaces', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('interfaces', 'meta')
    op.create_index('idx_devices_topology_vector', 'devices', ['topology_vector'], unique=False, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.create_index('idx_devices_security_vector', 'devices', ['security_vector'], unique=False, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.create_index('idx_devices_role_vector', 'devices', ['role_vector'], unique=False, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.create_index('idx_devices_config_vector', 'devices', ['config_vector'], unique=False, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.add_column('credentials', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('credentials', 'meta')
    op.drop_index('idx_audit_logs_timestamp', table_name='audit_logs')
    op.drop_index('idx_audit_logs_outcome', table_name='audit_logs')
    op.drop_index('idx_acl_snapshots_organization_id', table_name='acl_snapshots')
    op.drop_index('idx_acl_snapshots_device_id', table_name='acl_snapshots')
    op.drop_index('idx_acl_snapshots_content_type', table_name='acl_snapshots')
    op.drop_index('idx_acl_snapshots_compliance_scope', table_name='acl_snapshots', postgresql_using='gin')
    op.drop_index('idx_acl_snapshots_captured_at', table_name='acl_snapshots')
    op.drop_table('acl_snapshots')
    op.drop_index('idx_user_org_access_user_id', table_name='user_org_access')
    op.drop_index('idx_user_org_access_organization_id', table_name='user_org_access')
    op.drop_index('idx_user_org_access_expires_at', table_name='user_org_access')
    op.drop_table('user_org_access')
    op.drop_index('idx_tasks_status', table_name='tasks')
    op.drop_index('idx_tasks_parent_id', table_name='tasks')
    op.drop_index('idx_tasks_organization_id', table_name='tasks')
    op.drop_index('idx_tasks_created_at', table_name='tasks')
    op.drop_table('tasks')
    op.drop_index('idx_export_documents_status', table_name='export_documents')
    op.drop_index('idx_export_documents_requested_by', table_name='export_documents')
    op.drop_index('idx_export_documents_organization_id', table_name='export_documents')
    op.drop_index('idx_export_documents_expires_at', table_name='export_documents')
    op.drop_index('idx_export_documents_document_type', table_name='export_documents')
    op.drop_index('idx_export_documents_created_at', table_name='export_documents')
    op.drop_table('export_documents')
    op.drop_index('idx_change_records_status', table_name='change_records')
    op.drop_index('idx_change_records_requested_at', table_name='change_records')
    op.drop_index('idx_change_records_organization_id', table_name='change_records')
    op.drop_index('idx_change_records_external_ticket_id', table_name='change_records')
    op.drop_index('idx_change_records_change_number', table_name='change_records')
    op.drop_index('idx_change_records_approved_by', table_name='change_records')
    op.drop_index('idx_change_records_affected_compliance_scopes', table_name='change_records', postgresql_using='gin')
    op.drop_table('change_records')
    op.drop_index('idx_integration_configs_organization_id', table_name='integration_configs')
    op.drop_index('idx_integration_configs_is_enabled', table_name='integration_configs')
    op.drop_index('idx_integration_configs_integration_type', table_name='integration_configs')
    op.drop_table('integration_configs')
    # ### end Alembic commands ###
